import Head from 'next/head';
import Header from '@components/layouts/header';

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Dream Cars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        {children}
      </main>
    </>
  )
}
